#!/usr/bin/env node
'use strict';

// Aggregates <series>/stories/<id>.js source files into one browser-loadable <series>/stories.js,
// for a series that keeps one story per file (see japan-ehon/stories/README.md for that file
// format). A series that hand-maintains a single stories.js directly (taiwan-ehon) has no
// stories/ folder and is left untouched — this only ever touches a series that opts in.

const fs = require('node:fs');
const path = require('node:path');

const ROOT = path.join(__dirname, '..');
const SERIES = require('./registry.js');

function aggregate(seriesFolder) {
  const seriesDir = path.join(ROOT, seriesFolder);
  const storiesDir = path.join(seriesDir, 'stories');
  if (!fs.existsSync(storiesDir)) return null;
  const files = fs.readdirSync(storiesDir).filter(name => name.endsWith('.js')).sort();
  const stories = files.map(name => {
    const filePath = path.join(storiesDir, name);
    delete require.cache[require.resolve(filePath)];
    return require(filePath);
  });
  const ids = new Set();
  for (const story of stories) {
    if (!story || typeof story.id !== 'string' || !story.id) {
      throw new Error(`${seriesFolder}/stories: every file must export an object with a string "id"`);
    }
    if (ids.has(story.id)) throw new Error(`${seriesFolder}/stories: duplicate story id "${story.id}"`);
    ids.add(story.id);
  }
  const header = '// Generated by engine/build-stories.js from every file in stories/. Do not edit\n'
    + '// directly: add or change a story under stories/<id>.js and re-run the generator.\n';
  const body = "(function (root, stories) {\n"
    + "  if (typeof module === 'object' && module.exports) module.exports = stories;\n"
    + '  else root.EhonStories = stories;\n'
    + "})(typeof self !== 'undefined' ? self : this, "
    + `${JSON.stringify(stories, null, 2)});\n`;
  return header + body;
}

function build({ write = true } = {}) {
  const changed = [];
  for (const seriesFolder of SERIES) {
    const content = aggregate(seriesFolder);
    if (content === null) continue;
    const target = path.join(ROOT, seriesFolder, 'stories.js');
    const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : null;
    if (current === content) continue;
    changed.push(seriesFolder);
    if (write) fs.writeFileSync(target, content);
  }
  return changed;
}

if (require.main === module) {
  const check = process.argv.includes('--check');
  const changed = build({ write: !check });
  if (check && changed.length) {
    console.error(`stories.js out of sync with stories/*.js for: ${changed.join(', ')} (run node engine/build-stories.js)`);
    process.exit(1);
  }
  console.log(changed.length ? `Rebuilt stories.js for: ${changed.join(', ')}` : 'Every generated stories.js is already in sync.');
}

module.exports = { build, aggregate };
