// Generated by generate-audio-timing.js from this series' own audio/*.mp3 clips
// (probed with ffprobe) and engine/silence/*.mp3. Do not edit directly: regenerate this file
// instead — see engine/generate-audio-timing.js.
(function (root, data) {
  if (typeof module === 'object' && module.exports) module.exports = data;
  else root.EhonAudioTiming = data;
})(typeof self !== 'undefined' ? self : this, {
  "silence": {
    "language": 408,
    "sentence": 720,
    "page": 960
  },
  "stories": {}
});
