// Generated by engine/build-stories.js from every file in stories/. Do not edit
// directly: add or change a story under stories/<id>.js and re-run the generator.
(function (root, stories) {
  if (typeof module === 'object' && module.exports) module.exports = stories;
  else root.EhonStories = stories;
})(typeof self !== 'undefined' ? self : this, []);
